spring.application.name=food-delivery

spring.datasource.url=jdbc:postgresql://localhost:5432/food_delivery_db
spring.datasource.username=aarnitnair
spring.datasource.password=ecommerce123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8082